name: cardi_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.15.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  zoom_tap_animation: ^1.1.0
  appinio_video_player: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/edukasi/materi4/diet_garam_dan_cairan.mp4
